export enum WeaponType {
  BOW = 'WEAPON_BOW',
  CATALYST = 'WEAPON_CATALYST',
  CLAYMORE = 'WEAPON_CLAYMORE',
  POLE = 'WEAPON_POLE',
  SWORD_ONE_HAND = 'WEAPON_SWORD_ONE_HAND',
}

export enum QualityType {
  QUALITY_ORANGE = 'QUALITY_ORANGE',
  QUALITY_PURPLE = 'QUALITY_PURPLE',
  QUALITY_BLUE = 'QUALITY_BLUE',
  QUALITY_GREEN = 'QUALITY_GREEN',
  QUALITY_GREY = 'QUALITY_GREY',
}

export enum ElementType {
  ANEMO = 'ELEMENT_ANEMO',
  CRYO = 'ELEMENT_CRYO',
  DENDRO = 'ELEMENT_DENDRO',
  ELECTRO = 'ELEMENT_ELECTRO',
  GEO = 'ELEMENT_GEO',
  HYDRO = 'ELEMENT_HYDRO',
  NONE = 'ELEMENT_NONE',
  PYRO = 'ELEMENT_PYRO',
}
