export enum WeaponType {
  BOW = 'WEAPON_BOW',
  CATALYST = 'WEAPON_CATALYST',
  CLAYMORE = 'WEAPON_CLAYMORE',
  POLE = 'WEAPON_POLE',
  SWORD_ONE_HAND = 'WEAPON_SWORD_ONE_HAND',
}

export enum QualityType {
  QUALITY_ORANGE = 'QUALITY_ORANGE',
  QUALITY_PURPLE = 'QUALITY_PURPLE',
  QUALITY_BLUE = 'QUALITY_BLUE',
  QUALITY_GREEN = 'QUALITY_GREEN',
  QUALITY_GREY = 'QUALITY_GREY',
}

export enum ElementType {
  ANEMO = 'ELEMENT_ANEMO',
  CRYO = 'ELEMENT_CRYO',
  DENDRO = 'ELEMENT_DENDRO',
  ELECTRO = 'ELEMENT_ELECTRO',
  GEO = 'ELEMENT_GEO',
  HYDRO = 'ELEMENT_HYDRO',
  NONE = 'ELEMENT_NONE',
  PYRO = 'ELEMENT_PYRO',
}

export enum StatType {
  HP = 'FIGHT_PROP_HP',
  HP_P = 'FIGHT_PROP_HP_PERCENT',
  ATK = 'FIGHT_PROP_ATTACK',
  ATK_P = 'FIGHT_PROP_ATTACK_PERCENT',
  DEF = 'FIGHT_PROP_DEFENSE',
  DEF_P = 'FIGHT_PROP_DEFENSE_PERCENT',
  ER = 'FIGHT_PROP_CHARGE_EFFICIENCY',
  EM = 'FIGHT_PROP_ELEMENT_MASTERY',
  CR = 'FIGHT_PROP_CRITICAL',
  CD = 'FIGHT_PROP_CRITICAL_HURT',
  HB = 'FIGHT_PROP_HEAL_ADD',

  ELECTRO_P = 'FIGHT_PROP_ELEC_ADD_HURT',
  PYRO_P = 'FIGHT_PROP_FIRE_ADD_HURT',
  DENDRO_P = 'FIGHT_PROP_GRASS_ADD_HURT',
  CRYO_P = 'FIGHT_PROP_ICE_ADD_HURT',
  PHYS_P = 'FIGHT_PROP_PHYSICAL_ADD_HURT',
  GEO_P = 'FIGHT_PROP_ROCK_ADD_HURT',
  HYDRO_P = 'FIGHT_PROP_WATER_ADD_HURT',
  ANEMO_P = 'FIGHT_PROP_WIND_ADD_HURT',
}

export enum ArtifactType {
  FLOWER = 'EQUIP_BRACER',
  PLUME = 'EQUIP_NECKLACE',
  SANDS = 'EQUIP_SHOES',
  RING = 'EQUIP_RING',
  CIRCLET = 'EQUIP_DRESS',
}

export enum MaterialType {
  TALENT_MATERIAL = 'talent',
  BOSS_MATERIAL = 'boss',
  GEMSTONE = 'gemstone',
  LOCAL_SPECIALTY = 'local-specialty',
  WEAPON_MATERIAL = 'weapon',
  GENERIC_MATERIAL = 'generic',
  XP_AND_MORA = 'xp-and-mora',
}
